server:
  port: 9000

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/userdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  redis:
    host: 127.0.0.1
    port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.takeit: DEBUG

redirect:
  url: https://take-it.com:8080
